## Basic Configuration

baseurl = "https://pierrezemb.fr"
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Pierre Zemb"
title = "website"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
# googleAnalytics = "XYZ"
enableRobotsTXT = true
buildDrafts = true

## Site Settings
[params]
author = "Pierre Zemb"
intro = "Infrastructure Engineer"
description = "Currently working at [OVH](https://www.ovh.com/) on Metrics Data Platform.<br>Co-founder of [HelloExoWorld](https://helloexo.world).<br>Co-organizer of the [DevFest du Bout du Monde](https://devfest.duboutdumonde.bzh) and [FinistDevs](https://finistdevs.org/)"
authorimage = "myself.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Pierre Zemb"
keywords = "infrastructure,engineer,portfolio,developer,software,pierre,zemb,pierrez"

## Social Accounts
[params.social]
github = "PierreZ"
medium = "@PierreZ"
linkedin = "pierre-zemb-8004125b"
twitter = "PierreZ"
#facebook = "pierre.zemb"
#google = "pierre.zemb"
stackoverflow = "2477534"
hackernews = "PierreZ"
#steam = "pierrezemb"
reddit = "pierrezemb"
keybase = "PierreZ"
email = "contact@pierrezemb.fr"

## Extras
[params.extra]
copyright = "© 2019. Pierre Zemb. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true 
socialmarkup = true
rss = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 250
    url = "/posts/"

[[menu.main]]
    name = "Talks"
    identifier = "talks"
    weight = 300
    url = "/talks/"

[[menu.main]]
    name = "Résumé"
    identifier = "resume"
    weight = 310
    url = "/CV.pdf"