DefaultContentLanguage = "en"

baseURL = "https://pierrezemb.fr"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
ignoreErrors = ["error-remote-getjson"]
# language code
languageCode = "en"
title = "Pierre Zemb"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
# LoveIt theme version
version = "0.2.X"

enableGitInfo=true
enableEmoji=true
gitRepo = "https://github.com/PierreZ/pierrezemb.fr"

title = "Pierre Zemb"
description = "Pierre Zemb's personal blog"
dateFormat = "2006-01-02"
fingerprint = "sha256"

[author]
name = "Pierre Zemb"
link = "/"

# website images for Open Graph and Twitter Cards
images = ["/img/myself.jpg"]

[params.app]
title = "Pierre Zemb"
description = "Pierre Zemb's personal blog"

# Header config
[params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
    # URL of the LOGO
    logo = ""
    # title name
    name = "~/blog"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "👨‍💻"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
    typeit = true

# Footer config
[params.footer]
    enable = true
    custom = ''
    hugo = true
    copyright = true
    author = true
    since = 2015
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'


# Home page config
[params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = "pierre.zemb.isen@gmail.com"
    # URL of avatar shown in home page
    avatarURL = "/img/myself.jpg"
    # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
    title = "Pierre Zemb"
    # subtitle shown in home page
    subtitle = "Engineering Manager @ Clever Cloud </br> Distributed and Database systems"
    # whether to use typeit animation for subtitle
    typeit = false
    # whether to show social links
    social = true
    # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
    disclaimer = ""
    # Home page posts
    [params.home.posts]
    enable = true

[params.meta]
favicon = true


[outputs]
home = ["HTML", "RSS", "JSON"]

[params.search]
enable = true
# type of search engine ("lunr", "algolia")
type = "lunr"

[params.section]
# special amount of posts in each section page
paginate = 15

[params.page.share]
enable = true
Twitter = true
Facebook = true
Linkedin = true
HackerNews = true
Reddit = true

# Social config about the author
[params.social]
    RSS = true
    Twitter = "PierreZ"
    Github = "PierreZ"
    Keybase = "pierrez"
    Youtubechannel = "pierrezemb"
    Twitch = "PierreZemb"
    Linkedin = "%F0%9F%91%A8%F0%9F%8F%BB%E2%80%8D%F0%9F%92%BB-pierre-zemb-8004125b"

[params.social.Mastodon]
    id = "@PierreZ"
    prefix = "https://fosstodon.org/"

[menu]
    [[menu.main]]
        identifier = "About"
        # you can add extra information before the name (HTML format is supported), such as icons
        pre = ""
        # you can add extra information after the name (HTML format is supported), such as icons
        post = ""
        name = "About"
        url = "/about/"
        # title will be shown when you hover on this menu link
        title = ""
        weight = 1
    [[menu.main]]
        identifier = "Blog"
# you can add extra information before the name (HTML format is supported), such as icons
        pre = ""
        # you can add extra information after the name (HTML format is supported), such as icons
        post = ""
        name = "Blog"
        url = "/posts/"
        # title will be shown when you hover on this menu link
        title = ""
        weight = 2
    [[menu.main]]
        identifier = "podcast"
        pre = "️"
        post = ""
        name = "Podcasts"
        url = "/podcasts/"
        title = ""
        weight = 3
    [[menu.main]]
        identifier = "Talks"
        pre = ""
        post = ""
        name = "Talks"
        url = "/talks/"
        title = ""
        weight = 4
[[menu.main]]
        identifier = "categories"
        pre = "️"
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 5
[[menu.main]]
        identifier = "cv"
        pre = ""
        post = ""
        name = "Resume"
        url = "/cv.pdf"
        title = ""
        weight = 6

# Markup related configuration in Hugo
[markup]
# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false
