# https://codeberg.org/alanpearce/zola-bearblog/src/branch/main/config.toml
# The URL the site will be built for
base_url = "https://pierrezemb.fr"
title = "Pierre Zemb's Blog"
description = "Pierre Zemb personal blog"

theme = "zola-bearblog"

taxonomies = [
  { name = "tags", feed = true },
]

generate_feeds = true
feed_filenames = "atom.xml"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"

[[extra.main_menu]]
name = "Home"
url = "@/_index.md"

[[extra.main_menu]]
name = "Blog"
url = "@/posts/_index.md"

[[extra.main_menu]]
name = "Tags"
url = "/tags"

[[extra.main_menu]]
name = "Talks"
url = "@/talks.md"

[[extra.main_menu]]
name = "Podcasts"
url = "@/podcasts.md"

[[extra.main_menu]]
name = "Contact"
url = "@/contact.md"

[extra.table_of_contents]
show = true
max_level = 4
visible_on_load = true